twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['app/form_grid_type.html.twig', 'bootstrap_5_layout.html.twig']
    globals:
        role_ref: '@App\Util\RoleReference'
        user_menu: '@App\Util\UserMenu'
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'

when@test:
    twig:
        strict_variables: true
